name: Security Remediation Request
description: Request remediation for a security vulnerability
title: "[SECURITY] Remediate CVE-"
labels: ["security", "priority-critical"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Remediation Request
        Use this template to request remediation of a security vulnerability.
        
  - type: input
    id: cve-id
    attributes:
      label: CVE ID
      description: The CVE identifier for the vulnerability
      placeholder: "CVE-2025-66478"
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: CVSS severity rating
      options:
        - Critical (9.0-10.0)
        - High (7.0-8.9)
        - Medium (4.0-6.9)
        - Low (0.1-3.9)
    validations:
      required: true
      
  - type: textarea
    id: affected-packages
    attributes:
      label: Affected Packages
      description: List the vulnerable packages and their current versions
      placeholder: |
        - next@15.0.0
        - react@19.0.0
    validations:
      required: true
      
  - type: textarea
    id: remediation-steps
    attributes:
      label: Remediation Steps
      description: Known steps to remediate this vulnerability
      placeholder: |
        1. Run npm install next@15.0.5
        2. Verify with npm audit
        3. Test application
    validations:
      required: false
      
  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to advisories, documentation, etc.
      placeholder: |
        - https://nextjs.org/blog/CVE-2025-66478
        - https://react.dev/blog/2025/12/03/critical-security-vulnerability-in-react-server-components
    validations:
      required: false
      
  - type: checkboxes
    id: copilot-agent
    attributes:
      label: Automation Options
      description: Select if you'd like automated assistance
      options:
        - label: Request GitHub Copilot coding agent to create a remediation PR
          required: false
        - label: Notify security team
          required: false
